### PR TITLE
Adapted the search to use the search string converted to SLP1

### PR DESCRIPTION
**Pull request by claudius108**
References #1868.

### CODE REVIEW

**Comment by wolfgangmm** [comment]
@claudius108 @paddymcall I have trouble merging this because of the following missing module:

```xquery
import module namespace sarit-slp1 = "http://hra.uni-heidelberg.de/ns/sarit-transliteration";
```

**Comment by paddymcall** [comment]
On Sat, May 20 2017, Wolfgang Meier wrote:

> @claudius108 @paddymcall I have trouble merging this because of the
> following missing module:
> import module namespace sarit-slp1 = "http://hra.uni-heidelberg.de/ns/
> sarit-transliteration";

@wolfgangmm, you can get this module from here:
https://github.com/sarit/sarit-transliteration-exist-module

Something like this usually works for me:

git clone https://github.com/sarit/sarit-transliteration-exist-module.git
cd ./sarit-transliteration-exist-module/
mvn clean package
cp ./target/sarit-transliteration-exist-module-0.0.8.xar your/path/to/exist/autodeploy/

Plus, it depends on two libraries:

wget --quiet http://sanskritlibrary.org/software/transcodeFile.zip
unzip -q -u transcodeFile.zip
mvn install:install-file -Dfile=./TranscodeFile/dist/lib/SanskritLibrary.jar -DgroupId=org.sanskritlibrary -DartifactId=sl -Dversion=0.1 -Dpackaging=jar

And the Lucene transcoding analyzer:

git clone https://github.com/sarit/lucene-transcoding-analyzer.git
cd lucene-transcoding-analyzer/
mvn clean install -DskipTests


Hope this works for you,

--
Patrick

**Comment by wolfgangmm** [comment]
@paddymcall @claudius108 ok, I merged this branch after applying a bunch of fixes to adopt it to latest master. However, since you are using a specific lucene analyzer, I assume this has to be activated in a corresponding collection.xconf on the sarit-data package?

**Comment by wolfgangmm** [comment]
Oh, right, just saw your PR on sarit-data :-)

**Pull request merged**
